name: social_app
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.4.4 <4.0.0'

dependencies:
  animate_do: ^3.3.4
  animated_text_kit: ^4.2.2
  auto_route: ^8.2.0
  cupertino_icons: ^1.0.6
  dartz: ^0.10.1
  dio: ^5.7.0
  flutter:
    sdk: flutter
  flutter_animate: ^4.5.0
  flutter_bloc: ^8.1.6
  flutter_svg: ^2.0.10+1
  lottie: ^3.1.2
  shared_preferences: ^2.3.2
  flutter_launcher_icons: ^0.13.1
  flutter_native_splash: ^2.4.0

dev_dependencies:
  auto_route_generator: ^8.0.0
  build_runner: ^2.4.10
  flutter_gen_runner: ^5.8.0
  flutter_lints: ^3.0.0
  flutter_test:
    sdk: flutter
    

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/logo.png"
  min_sdk_android: 21 # android min sdk min:16, default 21

flutter_native_splash:
  color: "#ffffff"
  color_dark: "#ffffff"
  image: assets/images/logo.png
  android: true
  ios: true
  android_12:
    color: "#ffffff"
    icon_background_color_dark: "#ffffff"
    icon_background_color: "#ffffff"
    image: assets/images/logo.png # 1152 * 1152 => 768


flutter_gen:
  output: lib/core/gen/
  line_length: 80

  integrations:
    flutter_svg: true
    flare_flutter: true
    rive: true
    lottie: true

  colors:
    inputs:
      - assets/colors.xml

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/
    - assets/lottie/

  fonts:
    - family: Glory
      fonts:
        - asset: assets/fonts/Glory/Glory-Thin.ttf
          weight: 100
        - asset: assets/fonts/Glory/Glory-ExtraLight.ttf
          weight: 200
        - asset: assets/fonts/Glory/Glory-Light.ttf
          weight: 300
        - asset: assets/fonts/Glory/Glory-Regular.ttf
          weight: 400
        - asset: assets/fonts/Glory/Glory-Medium.ttf
          weight: 500
        - asset: assets/fonts/Glory/Glory-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Glory/Glory-Bold.ttf
          weight: 700
        - asset: assets/fonts/Glory/Glory-ExtraBold.ttf
          weight: 800